name: 전자정부프레엠웍을 사용하여 빌드 및 배포

on:
  push:
    branches:
      - main      # 주석 : main 브랜치에 push가 되면 actions가 동작함

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 Checkout
        uses: actions/checkout@v4

      - name: Java 8 설정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Maven 빌드
        run: mvn clean package

      - name: Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello:latest .

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 개인키 파일 생성
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: 서버 지문 등록
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: EC2 배포
        run: |
          ssh ubuntu@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hello:latest

            sudo docker stop hello || true
            sudo docker rm hello || true

            sudo docker run -d \
              --name hello \
              -p 80:8080 \
              --add-host=host.docker.internal:host-gateway \
              ${{ secrets.DOCKER_USERNAME }}/hello:latest
          EOF
    # - name: 개인키파일확인 
    #   run: |
    #     cat ~/.ssh/id_rsa
    #     cat ~/.ssh/known_hosts
      
        
