name: runners를 사용하여 빌드 및 배포

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, kosa-label]

    steps:
      - name: 소스 Checkout
        uses: actions/checkout@v4

      - name: Java 8 설정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Maven 빌드
        run: mvn clean package

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello:latest .

      - name: Docker 이미지 Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello:latest

      - name: 배포 실행
        run: |
          docker rm -f hello || true

          docker run -d \
            --name hello \
            -p 8080:8080 \
            --add-host=host.docker.internal:host-gateway \
            ${{ secrets.DOCKER_USERNAME }}/hello:latest
